// Copyright Natali Caggiano. All Rights Reserved.

#include "BlueprintGraphReader.h"
#include "BlueprintGraphEditor.h"

#include "Engine/Blueprint.h"
#include "Animation/AnimBlueprint.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Animation/AnimNodeBase.h"

// K2 nodes (BlueprintGraph module)
#include "K2Node.h"
#include "K2Node_Event.h"
#include "K2Node_CustomEvent.h"
#include "K2Node_CallFunction.h"
#include "K2Node_VariableGet.h"
#include "K2Node_VariableSet.h"
#include "K2Node_IfThenElse.h"
#include "K2Node_DynamicCast.h"
#include "K2Node_MacroInstance.h"
#include "K2Node_Knot.h"
#include "K2Node_FunctionEntry.h"
#include "K2Node_FunctionResult.h"
#include "K2Node_Self.h"
#include "K2Node_SwitchEnum.h"
#include "K2Node_Select.h"
#include "K2Node_MakeArray.h"
#include "K2Node_SpawnActorFromClass.h"
#include "K2Node_AssignmentStatement.h"
#include "K2Node_TemporaryVariable.h"

// Anim graph nodes (AnimGraph module)
#include "AnimGraphNode_Base.h"
#include "AnimGraphNode_Root.h"
#include "AnimGraphNode_StateResult.h"
#include "AnimGraphNode_TransitionResult.h"
#include "AnimGraphNode_StateMachine.h"
#include "AnimGraphNode_SequencePlayer.h"
#include "AnimGraphNode_BlendListByEnum.h"
#include "AnimGraphNode_BlendListByBool.h"
#include "AnimGraphNode_BlendSpacePlayer.h"
#include "Animation/BlendSpace.h"
#include "Animation/AnimationAsset.h"
#include "AnimGraphNode_LayeredBoneBlend.h"
#include "AnimGraphNode_SaveCachedPose.h"
#include "AnimGraphNode_UseCachedPose.h"
#include "AnimGraphNode_LinkedAnimGraph.h"
#include "AnimGraphNode_LinkedAnimLayer.h"
#include "AnimGraphNode_Slot.h"

// State machine
#include "AnimStateNode.h"
#include "AnimStateNodeBase.h"
#include "AnimStateEntryNode.h"
#include "AnimStateTransitionNode.h"
#include "AnimationStateMachineGraph.h"

// ============================================================================
// Operator Symbol Map
// ============================================================================

static TMap<FString, FString> InitOperatorMap()
{
	TMap<FString, FString> Map;
	Map.Add(TEXT("Greater"), TEXT(">"));
	Map.Add(TEXT("Less"), TEXT("<"));
	Map.Add(TEXT("Equal"), TEXT("=="));
	Map.Add(TEXT("EqualEqual"), TEXT("=="));
	Map.Add(TEXT("GreaterEqual"), TEXT(">="));
	Map.Add(TEXT("LessEqual"), TEXT("<="));
	Map.Add(TEXT("NotEqual"), TEXT("!="));
	Map.Add(TEXT("Add"), TEXT("+"));
	Map.Add(TEXT("Subtract"), TEXT("-"));
	Map.Add(TEXT("Multiply"), TEXT("*"));
	Map.Add(TEXT("Divide"), TEXT("/"));
	Map.Add(TEXT("BooleanAND"), TEXT("AND"));
	Map.Add(TEXT("BooleanOR"), TEXT("OR"));
	return Map;
}

static const TMap<FString, FString>& GetOperatorMap()
{
	static TMap<FString, FString> Map = InitOperatorMap();
	return Map;
}

// ============================================================================
// Pin Helpers
// ============================================================================

bool FBlueprintGraphReader::IsExecPin(UEdGraphPin* Pin)
{
	return Pin && Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec;
}

bool FBlueprintGraphReader::IsPoseLinkPin(UEdGraphPin* Pin)
{
	if (!Pin) return false;
	UObject* SubObj = Pin->PinType.PinSubCategoryObject.Get();
	UScriptStruct* Struct = Cast<UScriptStruct>(SubObj);
	if (!Struct) return false;
	static UScriptStruct* PoseLinkBase = FPoseLinkBase::StaticStruct();
	return Struct->IsChildOf(PoseLinkBase);
}

TArray<UEdGraphPin*> FBlueprintGraphReader::GetExecOutputPins(UEdGraphNode* Node)
{
	TArray<UEdGraphPin*> Result;
	if (!Node) return Result;
	for (UEdGraphPin* Pin : Node->Pins)
	{
		if (Pin->Direction == EGPD_Output && IsExecPin(Pin) && !Pin->bHidden)
		{
			Result.Add(Pin);
		}
	}
	return Result;
}

TArray<UEdGraphPin*> FBlueprintGraphReader::GetPoseInputPins(UEdGraphNode* Node)
{
	TArray<UEdGraphPin*> Result;
	if (!Node) return Result;
	for (UEdGraphPin* Pin : Node->Pins)
	{
		if (Pin->Direction == EGPD_Input && IsPoseLinkPin(Pin))
		{
			Result.Add(Pin);
		}
	}
	return Result;
}

TArray<UEdGraphPin*> FBlueprintGraphReader::GetDataInputPins(UEdGraphNode* Node)
{
	TArray<UEdGraphPin*> Result;
	if (!Node) return Result;
	for (UEdGraphPin* Pin : Node->Pins)
	{
		if (Pin->Direction == EGPD_Input
			&& !IsExecPin(Pin)
			&& !IsPoseLinkPin(Pin)
			&& !Pin->bHidden
			&& Pin->PinName != TEXT("self"))
		{
			// Only include if connected or has non-default value
			if (Pin->LinkedTo.Num() > 0)
			{
				Result.Add(Pin);
			}
			else if (!Pin->DefaultValue.IsEmpty() && Pin->DefaultValue != Pin->AutogeneratedDefaultValue)
			{
				Result.Add(Pin);
			}
		}
	}
	return Result;
}

UEdGraphNode* FBlueprintGraphReader::FollowThroughKnots(UEdGraphNode* Node, EEdGraphPinDirection Direction)
{
	if (!Node) return nullptr;

	UK2Node_Knot* Knot = Cast<UK2Node_Knot>(Node);
	int32 Safety = 100;
	while (Knot && Safety-- > 0)
	{
		UEdGraphNode* Next = nullptr;
		for (UEdGraphPin* Pin : Knot->Pins)
		{
			if (Pin->Direction == Direction && Pin->LinkedTo.Num() > 0)
			{
				Next = Pin->LinkedTo[0]->GetOwningNode();
				break;
			}
		}
		if (!Next) break;
		Knot = Cast<UK2Node_Knot>(Next);
		if (!Knot) return Next;
	}
	return Node;
}

// ============================================================================
// Graph Classification
// ============================================================================

FBlueprintGraphReader::EGraphType FBlueprintGraphReader::ClassifyGraph(UEdGraph* Graph)
{
	if (!Graph) return EGraphType::Other;

	for (UEdGraphNode* Node : Graph->Nodes)
	{
		if (Cast<UAnimGraphNode_Root>(Node))
		{
			return EGraphType::AnimGraph;
		}
		if (Cast<UAnimStateEntryNode>(Node))
		{
			return EGraphType::StateMachine;
		}
	}

	for (UEdGraphNode* Node : Graph->Nodes)
	{
		if (Cast<UAnimGraphNode_Base>(Node))
		{
			return EGraphType::AnimGraph;
		}
	}

	for (UEdGraphNode* Node : Graph->Nodes)
	{
		if (Cast<UK2Node_Event>(Node) || Cast<UK2Node_CustomEvent>(Node) || Cast<UK2Node_FunctionEntry>(Node))
		{
			return EGraphType::EventGraph;
		}
	}

	return EGraphType::Other;
}

// ============================================================================
// Node Labeling
// ============================================================================

FString FBlueprintGraphReader::GetNodeLabel(UEdGraphNode* Node)
{
	if (!Node) return FString();

	// Check for knot (reroute) nodes — return empty to skip
	if (Cast<UK2Node_Knot>(Node))
	{
		return FString();
	}

	// Try K2 node label first
	if (Cast<UK2Node>(Node))
	{
		return GetK2NodeLabel(Node);
	}

	// Try anim graph node label
	if (Cast<UAnimGraphNode_Base>(Node) || Cast<UAnimStateNodeBase>(Node) || Cast<UAnimStateEntryNode>(Node))
	{
		return GetAnimNodeLabel(Node);
	}

	// Fallback: use UE title
	return Node->GetNodeTitle(ENodeTitleType::ListView).ToString();
}

FString FBlueprintGraphReader::GetK2NodeLabel(UEdGraphNode* Node)
{
	// Event
	if (UK2Node_Event* Event = Cast<UK2Node_Event>(Node))
	{
		FName EventName = Event->EventReference.GetMemberName();
		return FString::Printf(TEXT("Event: %s"), *EventName.ToString());
	}

	// Custom Event
	if (UK2Node_CustomEvent* Custom = Cast<UK2Node_CustomEvent>(Node))
	{
		FName FuncName = Custom->CustomFunctionName;
		return FString::Printf(TEXT("CustomEvent: %s"), *FuncName.ToString());
	}

	// Function Entry
	if (UK2Node_FunctionEntry* FuncEntry = Cast<UK2Node_FunctionEntry>(Node))
	{
		FString FuncName = FuncEntry->FunctionReference.GetMemberName().ToString();
		if (FuncName.IsEmpty())
		{
			FuncName = FuncEntry->CustomGeneratedFunctionName.ToString();
		}
		return FString::Printf(TEXT("FunctionEntry: %s"), *FuncName);
	}

	// Function Result
	if (Cast<UK2Node_FunctionResult>(Node))
	{
		return TEXT("FunctionResult");
	}

	// Call Function
	if (UK2Node_CallFunction* Call = Cast<UK2Node_CallFunction>(Node))
	{
		FName FuncName = Call->FunctionReference.GetMemberName();
		UClass* MemberParent = Call->FunctionReference.GetMemberParentClass();
		if (MemberParent)
		{
			return FString::Printf(TEXT("Call %s::%s()"), *MemberParent->GetName(), *FuncName.ToString());
		}
		return FString::Printf(TEXT("Call %s()"), *FuncName.ToString());
	}

	// Variable Get/Set
	if (UK2Node_VariableGet* VarGet = Cast<UK2Node_VariableGet>(Node))
	{
		return FString::Printf(TEXT("Get %s"), *VarGet->GetVarName().ToString());
	}
	if (UK2Node_VariableSet* VarSet = Cast<UK2Node_VariableSet>(Node))
	{
		return FString::Printf(TEXT("Set %s"), *VarSet->GetVarName().ToString());
	}

	// Branch
	if (Cast<UK2Node_IfThenElse>(Node))
	{
		return TEXT("Branch");
	}

	// Cast
	if (UK2Node_DynamicCast* DynCast = Cast<UK2Node_DynamicCast>(Node))
	{
		UClass* TargetClass = DynCast->TargetType;
		return FString::Printf(TEXT("Cast to %s"), TargetClass ? *TargetClass->GetName() : TEXT("???"));
	}

	// Macro
	if (UK2Node_MacroInstance* Macro = Cast<UK2Node_MacroInstance>(Node))
	{
		UEdGraph* MacroGraph = Macro->GetMacroGraph();
		FString MacroName = MacroGraph ? MacroGraph->GetName() : TEXT("Unknown");
		return FString::Printf(TEXT("Macro: %s"), *MacroName);
	}

	// Switch
	if (Cast<UK2Node_SwitchEnum>(Node))
	{
		return TEXT("Switch on Enum");
	}

	// Self
	if (Cast<UK2Node_Self>(Node))
	{
		return TEXT("Self");
	}

	// Select
	if (Cast<UK2Node_Select>(Node))
	{
		return TEXT("Select");
	}

	// Make Array
	if (Cast<UK2Node_MakeArray>(Node))
	{
		return TEXT("Make Array");
	}

	// Spawn Actor
	if (Cast<UK2Node_SpawnActorFromClass>(Node))
	{
		return TEXT("Spawn Actor");
	}

	// Assignment
	if (Cast<UK2Node_AssignmentStatement>(Node))
	{
		return TEXT("Assign");
	}

	// Temp Variable
	if (Cast<UK2Node_TemporaryVariable>(Node))
	{
		return TEXT("TempVar");
	}

	// Fallback: use node title
	FText Title = Node->GetNodeTitle(ENodeTitleType::ListView);
	if (!Title.IsEmpty())
	{
		return Title.ToString();
	}

	return Node->GetClass()->GetName();
}

FString FBlueprintGraphReader::GetAnimNodeLabel(UEdGraphNode* Node)
{
	// Root output pose
	if (Cast<UAnimGraphNode_Root>(Node))
	{
		return TEXT("Output Pose");
	}

	// State result (output pose in state)
	if (Cast<UAnimGraphNode_StateResult>(Node))
	{
		return TEXT("Output Pose");
	}

	// Transition result
	if (Cast<UAnimGraphNode_TransitionResult>(Node))
	{
		return TEXT("Transition Result");
	}

	// State machine
	if (UAnimGraphNode_StateMachine* SM = Cast<UAnimGraphNode_StateMachine>(Node))
	{
		FString SMName = SM->GetNodeTitle(ENodeTitleType::ListView).ToString();
		if (SMName.IsEmpty())
		{
			SMName = SM->GetStateMachineName();
		}
		return FString::Printf(TEXT("State Machine: %s"), *SMName);
	}

	// Slot
	if (UAnimGraphNode_Slot* Slot = Cast<UAnimGraphNode_Slot>(Node))
	{
		FString SlotName = Slot->Node.SlotName.ToString();
		return FString::Printf(TEXT("Slot (%s)"), *SlotName);
	}

	// Save cached pose
	if (UAnimGraphNode_SaveCachedPose* SavePose = Cast<UAnimGraphNode_SaveCachedPose>(Node))
	{
		return FString::Printf(TEXT("Save Cached Pose: %s"), *SavePose->CacheName);
	}

	// Use cached pose
	if (UAnimGraphNode_UseCachedPose* UsePose = Cast<UAnimGraphNode_UseCachedPose>(Node))
	{
		FString LinkName = UsePose->GetNodeTitle(ENodeTitleType::ListView).ToString();
		return FString::Printf(TEXT("Use Cached Pose: %s"), *LinkName);
	}

	// State node (in state machine)
	if (UAnimStateNode* StateNode = Cast<UAnimStateNode>(Node))
	{
		return FString::Printf(TEXT("State: %s"),
			*StateNode->GetNodeTitle(ENodeTitleType::ListView).ToString());
	}

	// Entry node
	if (Cast<UAnimStateEntryNode>(Node))
	{
		return TEXT("Entry");
	}

	// Transition node
	if (UAnimStateTransitionNode* Trans = Cast<UAnimStateTransitionNode>(Node))
	{
		if (Trans->bAutomaticRuleBasedOnSequencePlayerInState)
		{
			return TEXT("Transition [automatic]");
		}
		return TEXT("Transition");
	}

	// Linked Anim Layer
	if (UAnimGraphNode_LinkedAnimLayer* LayerNode = Cast<UAnimGraphNode_LinkedAnimLayer>(Node))
	{
		FName LayerName = LayerNode->Node.Layer;
		UClass* InterfaceClass = *LayerNode->Node.Interface;
		if (InterfaceClass)
		{
			return FString::Printf(TEXT("Linked Anim Layer: %s (Interface: %s)"),
				*LayerName.ToString(), *InterfaceClass->GetName());
		}
		return FString::Printf(TEXT("Anim Layer (self): %s"), *LayerName.ToString());
	}

	// For all other anim graph nodes, use the node title (which is typically good)
	if (UAnimGraphNode_Base* AnimNode = Cast<UAnimGraphNode_Base>(Node))
	{
		FText Title = AnimNode->GetNodeTitle(ENodeTitleType::ListView);
		if (!Title.IsEmpty())
		{
			return Title.ToString();
		}
	}

	return Node->GetNodeTitle(ENodeTitleType::ListView).ToString();
}

// ============================================================================
// EventGraph Walking
// ============================================================================

FString FBlueprintGraphReader::GetDataInputSummary(UEdGraphNode* Node)
{
	TArray<UEdGraphPin*> DataPins = GetDataInputPins(Node);
	if (DataPins.Num() == 0) return FString();

	TArray<FString> Parts;
	for (UEdGraphPin* Pin : DataPins)
	{
		FString PinLabel = Pin->GetDisplayName().IsEmpty()
			? Pin->PinName.ToString()
			: Pin->GetDisplayName().ToString();

		if (Pin->LinkedTo.Num() > 0)
		{
			UEdGraphNode* SourceNode = FollowThroughKnots(Pin->LinkedTo[0]->GetOwningNode(), EGPD_Input);
			FString SourceLabel = GetNodeLabel(SourceNode);
			if (!SourceLabel.IsEmpty())
			{
				Parts.Add(FString::Printf(TEXT("%s=%s"), *PinLabel, *SourceLabel));
			}
			else
			{
				Parts.Add(FString::Printf(TEXT("%s=<connected>"), *PinLabel));
			}
		}
		else if (!Pin->DefaultValue.IsEmpty())
		{
			Parts.Add(FString::Printf(TEXT("%s=%s"), *PinLabel, *Pin->DefaultValue));
		}
	}

	if (Parts.Num() == 0) return FString();
	return FString::Printf(TEXT("  (%s)"), *FString::Join(Parts, TEXT(", ")));
}

void FBlueprintGraphReader::WalkExecChain(UEdGraphNode* Node, int32 Depth, FString& Output, TSet<UEdGraphNode*>& Visited, TArray<FString>* OutVisitedIds)
{
	if (!Node) return;

	// Resolve through knots
	Node = FollowThroughKnots(Node, EGPD_Output);
	if (!Node) return;

	if (Visited.Contains(Node))
	{
		FString Prefix = FString::ChrN(Depth * 2, TEXT(' '));
		Output += FString::Printf(TEXT("%s-> (cycle)\n"), *Prefix);
		return;
	}
	Visited.Add(Node);

	FString Label = GetNodeLabel(Node);

	// Skip nodes with no label (knots, etc.)
	if (Label.IsEmpty())
	{
		TArray<UEdGraphPin*> ExecOuts = GetExecOutputPins(Node);
		for (UEdGraphPin* ExecOut : ExecOuts)
		{
			for (UEdGraphPin* LinkedPin : ExecOut->LinkedTo)
			{
				WalkExecChain(LinkedPin->GetOwningNode(), Depth, Output, Visited, OutVisitedIds);
			}
		}
		return;
	}

	FString NodeId = FBlueprintGraphEditor::GetNodeId(Node);
	if (NodeId.IsEmpty())
	{
		NodeId = Node->GetName();
	}

	if (OutVisitedIds && !NodeId.IsEmpty())
	{
		OutVisitedIds->AddUnique(NodeId);
	}

	if (!NodeId.IsEmpty())
	{
		Label += FString::Printf(TEXT(" [id:%s]"), *NodeId);
	}

	// Append data input summary
	Label += GetDataInputSummary(Node);

	// Output this node
	FString Prefix = FString::ChrN(Depth * 2, TEXT(' '));
	if (Depth == 0)
	{
		Output += FString::Printf(TEXT("%s%s\n"), *Prefix, *Label);
	}
	else
	{
		Output += FString::Printf(TEXT("%sthen -> %s\n"), *Prefix, *Label);
	}

	// Follow exec output pins
	TArray<UEdGraphPin*> ExecOuts = GetExecOutputPins(Node);
	if (ExecOuts.Num() == 1)
	{
		for (UEdGraphPin* LinkedPin : ExecOuts[0]->LinkedTo)
		{
			WalkExecChain(LinkedPin->GetOwningNode(), Depth + 1, Output, Visited, OutVisitedIds);
		}
	}
	else if (ExecOuts.Num() > 1)
	{
		for (UEdGraphPin* ExecOut : ExecOuts)
		{
			if (ExecOut->LinkedTo.Num() == 0) continue;

			FString PinLabel = ExecOut->GetDisplayName().IsEmpty()
				? ExecOut->PinName.ToString()
				: ExecOut->GetDisplayName().ToString();

			Output += FString::Printf(TEXT("%s  [%s]:\n"), *Prefix, *PinLabel);
			for (UEdGraphPin* LinkedPin : ExecOut->LinkedTo)
			{
				WalkExecChain(LinkedPin->GetOwningNode(), Depth + 2, Output, Visited, OutVisitedIds);
			}
		}
	}
}

// ============================================================================
// AnimGraph Walking
// ============================================================================

FString FBlueprintGraphReader::GetBlendPinLabel(UEdGraphPin* Pin, UEdGraphNode* OwnerNode)
{
	if (!Pin) return FString();

	// Use display name if available
	FText DisplayName = Pin->GetDisplayName();
	if (!DisplayName.IsEmpty())
	{
		return DisplayName.ToString();
	}

	// For blend-by-enum nodes, try to map the index to enum entry
	FString PinName = Pin->PinName.ToString();
	if (PinName.StartsWith(TEXT("BlendPose_")))
	{
		// Extract index
		FString IndexStr = PinName.RightChop(10); // "BlendPose_" is 10 chars
		int32 Index = FCString::Atoi(*IndexStr);
		if (Index == 0)
		{
			return TEXT("Default");
		}
	}

	if (PinName == TEXT("Source") || PinName == TEXT("Result") || PinName == TEXT("Pose"))
	{
		return PinName;
	}

	return PinName;
}

void FBlueprintGraphReader::WalkPoseChain(UEdGraphNode* Node, int32 Depth, FString& Output,
	TSet<UEdGraphNode*>& Visited, const FString& PinLabel)
{
	if (!Node) return;

	if (Visited.Contains(Node))
	{
		FString Prefix = FString::ChrN(Depth * 2, TEXT(' '));
		FString LabelStr = PinLabel.IsEmpty() ? FString() : FString::Printf(TEXT("[%s] "), *PinLabel);
		Output += FString::Printf(TEXT("%s%s(cycle)\n"), *Prefix, *LabelStr);
		return;
	}
	Visited.Add(Node);

	FString Label = GetNodeLabel(Node);
	FString Prefix = FString::ChrN(Depth * 2, TEXT(' '));
	FString LabelStr = PinLabel.IsEmpty() ? FString() : FString::Printf(TEXT("[%s] "), *PinLabel);

	// Collect data input pins for context
	TArray<FString> DataParts;
	for (UEdGraphPin* Pin : Node->Pins)
	{
		if (Pin->Direction == EGPD_Input && !IsExecPin(Pin) && !IsPoseLinkPin(Pin)
			&& !Pin->bHidden && Pin->PinName != TEXT("self"))
		{
			FString DPinName = Pin->GetDisplayName().IsEmpty() ? Pin->PinName.ToString() : Pin->GetDisplayName().ToString();
			if (Pin->LinkedTo.Num() > 0)
			{
				UEdGraphNode* Src = FollowThroughKnots(Pin->LinkedTo[0]->GetOwningNode(), EGPD_Input);
				FString SrcLabel = GetNodeLabel(Src);
				DataParts.Add(FString::Printf(TEXT("%s <- %s"), *DPinName, SrcLabel.IsEmpty() ? TEXT("???") : *SrcLabel));
			}
			else
			{
				FString DefaultVal = Pin->DefaultValue.IsEmpty() ? TEXT("0") : Pin->DefaultValue;
				DataParts.Add(FString::Printf(TEXT("%s [UNWIRED=%s]"), *DPinName, *DefaultVal));
			}
		}
	}
	FString DataSuffix = DataParts.Num() > 0
		? FString::Printf(TEXT("  (%s)"), *FString::Join(DataParts, TEXT(", ")))
		: FString();

	Output += FString::Printf(TEXT("%s%s%s%s\n"), *Prefix, *LabelStr, *Label, *DataSuffix);

	// Walk pose input pins backward
	TArray<UEdGraphPin*> PoseInputs = GetPoseInputPins(Node);

	if (PoseInputs.Num() == 1)
	{
		for (UEdGraphPin* LinkedPin : PoseInputs[0]->LinkedTo)
		{
			WalkPoseChain(LinkedPin->GetOwningNode(), Depth + 1, Output, Visited);
		}
	}
	else if (PoseInputs.Num() > 1)
	{
		for (UEdGraphPin* PosePin : PoseInputs)
		{
			FString BlendLabel = GetBlendPinLabel(PosePin, Node);
			if (PosePin->LinkedTo.Num() > 0)
			{
				for (UEdGraphPin* LinkedPin : PosePin->LinkedTo)
				{
					WalkPoseChain(LinkedPin->GetOwningNode(), Depth + 1, Output, Visited, BlendLabel);
				}
			}
			else
			{
				Output += FString::Printf(TEXT("%s  [%s] (not connected)\n"), *Prefix, *BlendLabel);
			}
		}
	}
}

// ============================================================================
// State Machine
// ============================================================================

FString FBlueprintGraphReader::ResolveOperatorSymbol(const FString& FuncName)
{
	const TMap<FString, FString>& OpMap = GetOperatorMap();

	if (const FString* Symbol = OpMap.Find(FuncName))
	{
		return *Symbol;
	}

	// Try stripping type suffix (e.g., "Greater_FloatFloat" -> "Greater")
	int32 UnderscoreIdx;
	if (FuncName.FindChar(TEXT('_'), UnderscoreIdx))
	{
		FString Base = FuncName.Left(UnderscoreIdx);
		if (const FString* Symbol = OpMap.Find(Base))
		{
			return *Symbol;
		}
	}

	return FString();
}

FString FBlueprintGraphReader::BuildExpression(UEdGraphNode* Node, TSet<UEdGraphNode*>& Visited)
{
	if (!Node) return TEXT("???");

	if (Visited.Contains(Node))
	{
		return TEXT("(cycle)");
	}
	Visited.Add(Node);

	// Knots — follow through
	if (UK2Node_Knot* Knot = Cast<UK2Node_Knot>(Node))
	{
		for (UEdGraphPin* Pin : Knot->Pins)
		{
			if (Pin->Direction == EGPD_Input && Pin->LinkedTo.Num() > 0)
			{
				return BuildExpression(Pin->LinkedTo[0]->GetOwningNode(), Visited);
			}
		}
		return TEXT("???");
	}

	// Variable get
	if (UK2Node_VariableGet* VarGet = Cast<UK2Node_VariableGet>(Node))
	{
		return VarGet->GetVarName().ToString();
	}

	// Call function (operators, NOT, etc.)
	if (UK2Node_CallFunction* CallFunc = Cast<UK2Node_CallFunction>(Node))
	{
		FName MemberName = CallFunc->FunctionReference.GetMemberName();
		FString FuncName = MemberName.ToString();

		// Unary NOT
		if (FuncName == TEXT("Not_PreBool"))
		{
			for (UEdGraphPin* Pin : Node->Pins)
			{
				if (Pin->Direction == EGPD_Input && !IsExecPin(Pin) && Pin->PinName != TEXT("self"))
				{
					if (Pin->LinkedTo.Num() > 0)
					{
						return FString::Printf(TEXT("NOT %s"),
							*BuildExpression(Pin->LinkedTo[0]->GetOwningNode(), Visited));
					}
				}
			}
			return TEXT("NOT ???");
		}

		// Binary operator
		FString OpSymbol = ResolveOperatorSymbol(FuncName);
		if (!OpSymbol.IsEmpty())
		{
			TArray<FString> Operands;
			for (UEdGraphPin* Pin : Node->Pins)
			{
				if (Pin->Direction == EGPD_Input && !IsExecPin(Pin)
					&& Pin->PinName != TEXT("self") && Pin->PinName != TEXT("ErrorTolerance"))
				{
					if (Pin->LinkedTo.Num() > 0)
					{
						Operands.Add(BuildExpression(Pin->LinkedTo[0]->GetOwningNode(), Visited));
					}
					else if (!Pin->DefaultValue.IsEmpty())
					{
						Operands.Add(Pin->DefaultValue);
					}
					else
					{
						// Default for numeric/bool
						FString Cat = Pin->PinType.PinCategory.ToString();
						if (Cat == TEXT("bool"))
							Operands.Add(TEXT("false"));
						else
							Operands.Add(TEXT("0"));
					}
				}
			}
			if (Operands.Num() >= 2)
			{
				return FString::Printf(TEXT("%s %s %s"), *Operands[0], *OpSymbol, *Operands[1]);
			}
			if (Operands.Num() == 1)
			{
				return FString::Printf(TEXT("%s %s 0"), *Operands[0], *OpSymbol);
			}
			return OpSymbol;
		}

		return FuncName;
	}

	// Fallback: use node title
	FText Title = Node->GetNodeTitle(ENodeTitleType::ListView);
	return Title.IsEmpty() ? Node->GetName() : Title.ToString();
}

FString FBlueprintGraphReader::BuildTransitionRuleExpression(UEdGraph* TransitionGraph)
{
	if (!TransitionGraph) return TEXT("(no rule graph)");

	// Find TransitionResult node
	UAnimGraphNode_TransitionResult* ResultNode = nullptr;
	for (UEdGraphNode* Node : TransitionGraph->Nodes)
	{
		if (UAnimGraphNode_TransitionResult* TR = Cast<UAnimGraphNode_TransitionResult>(Node))
		{
			ResultNode = TR;
			break;
		}
	}

	if (!ResultNode) return TEXT("(no transition result)");

	// Find the boolean input pin and walk backward
	for (UEdGraphPin* Pin : ResultNode->Pins)
	{
		if (Pin->Direction == EGPD_Input && !IsExecPin(Pin) && Pin->PinName != TEXT("self"))
		{
			if (Pin->LinkedTo.Num() > 0)
			{
				TSet<UEdGraphNode*> Visited;
				return BuildExpression(Pin->LinkedTo[0]->GetOwningNode(), Visited);
			}
			if (!Pin->DefaultValue.IsEmpty())
			{
				return Pin->DefaultValue;
			}
		}
	}

	return TEXT("(no rule)");
}

void FBlueprintGraphReader::FormatStateMachine(UAnimGraphNode_StateMachine* SMNode, FString& Output,
	TSharedPtr<FJsonObject>& SMMetadata)
{
	if (!SMNode) return;

	UAnimationStateMachineGraph* SMGraph = SMNode->EditorStateMachineGraph;
	if (!SMGraph) return;

	FString SMName = SMNode->GetStateMachineName();
	Output += FString::Printf(TEXT("\n=== State Machine: %s ===\n\n"), *SMName);

	SMMetadata = MakeShared<FJsonObject>();
	SMMetadata->SetStringField(TEXT("name"), SMName);

	// Collect states and entry
	TMap<UEdGraphNode*, FString> StateNames;
	UAnimStateEntryNode* EntryNode = nullptr;
	TArray<UAnimStateTransitionNode*> Transitions;

	for (UEdGraphNode* Node : SMGraph->Nodes)
	{
		if (UAnimStateNode* StateNode = Cast<UAnimStateNode>(Node))
		{
			FString StateName = StateNode->GetNodeTitle(ENodeTitleType::ListView).ToString();
			StateNames.Add(Node, StateName);
		}
		else if (UAnimStateEntryNode* Entry = Cast<UAnimStateEntryNode>(Node))
		{
			EntryNode = Entry;
		}
		else if (UAnimStateTransitionNode* Trans = Cast<UAnimStateTransitionNode>(Node))
		{
			Transitions.Add(Trans);
		}
	}

	// Entry state
	FString EntryStateName;
	if (EntryNode)
	{
		for (UEdGraphPin* Pin : EntryNode->Pins)
		{
			if (Pin->Direction == EGPD_Output && Pin->LinkedTo.Num() > 0)
			{
				UEdGraphNode* TargetNode = Pin->LinkedTo[0]->GetOwningNode();
				if (FString* Name = StateNames.Find(TargetNode))
				{
					EntryStateName = *Name;
				}
				break;
			}
		}
	}

	if (!EntryStateName.IsEmpty())
	{
		Output += FString::Printf(TEXT("Entry -> %s\n\n"), *EntryStateName);
		SMMetadata->SetStringField(TEXT("entry_state"), EntryStateName);
	}

	// Transitions
	if (Transitions.Num() > 0)
	{
		Output += TEXT("Transitions:\n");
		TArray<TSharedPtr<FJsonValue>> TransArray;

		for (UAnimStateTransitionNode* Trans : Transitions)
		{
			FString Source, Target;

			for (UEdGraphPin* Pin : Trans->Pins)
			{
				for (UEdGraphPin* LinkedPin : Pin->LinkedTo)
				{
					UEdGraphNode* LinkedNode = LinkedPin->GetOwningNode();
					if (FString* Name = StateNames.Find(LinkedNode))
					{
						if (Pin->Direction == EGPD_Input)
						{
							Source = *Name;
						}
						else
						{
							Target = *Name;
						}
					}
				}
			}

			FString Rule;
			if (Trans->bAutomaticRuleBasedOnSequencePlayerInState)
			{
				Rule = TEXT("[automatic - sequence player finished]");
			}
			else
			{
				UEdGraph* TransGraph = Trans->GetBoundGraph();
				Rule = BuildTransitionRuleExpression(TransGraph);
			}

			Output += FString::Printf(TEXT("  %s -> %s:  %s\n"),
				Source.IsEmpty() ? TEXT("???") : *Source,
				Target.IsEmpty() ? TEXT("???") : *Target,
				*Rule);

			TSharedPtr<FJsonObject> TransJson = MakeShared<FJsonObject>();
			TransJson->SetStringField(TEXT("source"), Source.IsEmpty() ? TEXT("???") : Source);
			TransJson->SetStringField(TEXT("target"), Target.IsEmpty() ? TEXT("???") : Target);
			TransJson->SetStringField(TEXT("rule"), Rule);
			TransArray.Add(MakeShared<FJsonValueObject>(TransJson));
		}

		SMMetadata->SetNumberField(TEXT("transition_count"), Transitions.Num());
		SMMetadata->SetArrayField(TEXT("transitions"), TransArray);
		Output += TEXT("\n");
	}

	// States with their animations
	if (StateNames.Num() > 0)
	{
		Output += TEXT("States:\n");
		TArray<TSharedPtr<FJsonValue>> StateArray;

		// Sort states by name
		TArray<TPair<UEdGraphNode*, FString>> SortedStates;
		for (auto& Pair : StateNames)
		{
			SortedStates.Add(TPair<UEdGraphNode*, FString>(Pair.Key, Pair.Value));
		}
		SortedStates.Sort([](const auto& A, const auto& B) { return A.Value < B.Value; });

		for (auto& Pair : SortedStates)
		{
			UAnimStateNode* StateNode = Cast<UAnimStateNode>(Pair.Key);
			FString StateName = Pair.Value;

			Output += FString::Printf(TEXT("  %s:\n"), *StateName);
			StateArray.Add(MakeShared<FJsonValueString>(StateName));

			if (StateNode)
			{
				UEdGraph* StateGraph = StateNode->GetBoundGraph();
				if (StateGraph)
				{
					// Find StateResult node and walk pose chain
					for (UEdGraphNode* Node : StateGraph->Nodes)
					{
						if (Cast<UAnimGraphNode_StateResult>(Node))
						{
							TSet<UEdGraphNode*> Visited;
							FString PoseOutput;
							WalkPoseChain(Node, 0, PoseOutput, Visited);

							// Indent state animation
							TArray<FString> Lines;
							PoseOutput.ParseIntoArrayLines(Lines);
							for (const FString& Line : Lines)
							{
								if (!Line.IsEmpty())
								{
									Output += FString::Printf(TEXT("    %s\n"), *Line);
								}
							}
							break;
						}
					}
				}
				else
				{
					Output += TEXT("    (no state graph)\n");
				}
			}
		}

		SMMetadata->SetNumberField(TEXT("state_count"), StateNames.Num());
		SMMetadata->SetArrayField(TEXT("states"), StateArray);
		Output += TEXT("\n");
	}
}

// ============================================================================
// K2 Node Serialization
// ============================================================================

void FBlueprintGraphReader::DeriveK2NodeTypeAndContext(UEdGraphNode* Node, FString& OutNodeType, FString& OutContext)
{
	OutNodeType = TEXT("Node");
	OutContext = FString();

	if (UK2Node_Event* Event = Cast<UK2Node_Event>(Node))
	{
		OutNodeType = TEXT("Event");
		OutContext = Event->EventReference.GetMemberName().ToString();
	}
	else if (UK2Node_CustomEvent* Custom = Cast<UK2Node_CustomEvent>(Node))
	{
		OutNodeType = TEXT("CustomEvent");
		OutContext = Custom->CustomFunctionName.ToString();
	}
	else if (UK2Node_FunctionEntry* FuncEntry = Cast<UK2Node_FunctionEntry>(Node))
	{
		OutNodeType = TEXT("FunctionEntry");
		FString FuncName = FuncEntry->FunctionReference.GetMemberName().ToString();
		if (FuncName.IsEmpty()) FuncName = FuncEntry->CustomGeneratedFunctionName.ToString();
		OutContext = FuncName;
	}
	else if (Cast<UK2Node_FunctionResult>(Node))
	{
		OutNodeType = TEXT("FunctionResult");
	}
	else if (UK2Node_CallFunction* Call = Cast<UK2Node_CallFunction>(Node))
	{
		OutNodeType = TEXT("CallFunction");
		OutContext = Call->FunctionReference.GetMemberName().ToString();
	}
	else if (UK2Node_VariableGet* VarGet = Cast<UK2Node_VariableGet>(Node))
	{
		OutNodeType = TEXT("VarGet");
		OutContext = VarGet->GetVarName().ToString();
	}
	else if (UK2Node_VariableSet* VarSet = Cast<UK2Node_VariableSet>(Node))
	{
		OutNodeType = TEXT("VarSet");
		OutContext = VarSet->GetVarName().ToString();
	}
	else if (Cast<UK2Node_IfThenElse>(Node))
	{
		OutNodeType = TEXT("Branch");
	}
	else if (UK2Node_DynamicCast* DynCast = Cast<UK2Node_DynamicCast>(Node))
	{
		OutNodeType = TEXT("Cast");
		if (DynCast->TargetType)
		{
			OutContext = DynCast->TargetType->GetName();
		}
	}
	else if (UK2Node_MacroInstance* Macro = Cast<UK2Node_MacroInstance>(Node))
	{
		OutNodeType = TEXT("Macro");
		UEdGraph* MacroGraph = Macro->GetMacroGraph();
		if (MacroGraph) OutContext = MacroGraph->GetName();
	}
	else if (Cast<UK2Node_SwitchEnum>(Node))
	{
		OutNodeType = TEXT("SwitchEnum");
	}
	else if (Cast<UK2Node_SpawnActorFromClass>(Node))
	{
		OutNodeType = TEXT("SpawnActor");
	}
	else if (Cast<UK2Node_AssignmentStatement>(Node))
	{
		OutNodeType = TEXT("Assign");
	}
	else if (Cast<UK2Node_MakeArray>(Node))
	{
		OutNodeType = TEXT("MakeArray");
	}
	else if (Cast<UK2Node_Select>(Node))
	{
		OutNodeType = TEXT("Select");
	}
	else if (Cast<UK2Node_Self>(Node))
	{
		OutNodeType = TEXT("Self");
	}

	OutContext.ReplaceInline(TEXT(" "), TEXT("_"));
}

TSharedPtr<FJsonObject> FBlueprintGraphReader::SerializeK2NodeInfo(UEdGraphNode* Node, UEdGraph* Graph)
{
	TSharedPtr<FJsonObject> Json = MakeShared<FJsonObject>();
	if (!Node) return Json;

	FString NodeId = FBlueprintGraphEditor::GetNodeId(Node);
	if (NodeId.IsEmpty())
	{
		FString NodeType, Context;
		DeriveK2NodeTypeAndContext(Node, NodeType, Context);
		NodeId = FBlueprintGraphEditor::GenerateNodeId(NodeType, Context, Graph);
		FBlueprintGraphEditor::SetNodeId(Node, NodeId);
	}

	Json->SetStringField(TEXT("node_id"), NodeId);
	Json->SetStringField(TEXT("node_class"), Node->GetClass()->GetName());
	Json->SetStringField(TEXT("label"), GetK2NodeLabel(Node));
	Json->SetNumberField(TEXT("pos_x"), Node->NodePosX);
	Json->SetNumberField(TEXT("pos_y"), Node->NodePosY);

	TArray<TSharedPtr<FJsonValue>> PinsArray;
	for (UEdGraphPin* Pin : Node->Pins)
	{
		if (!Pin || Pin->bHidden) continue;

		TSharedPtr<FJsonObject> PinJson = MakeShared<FJsonObject>();
		PinJson->SetStringField(TEXT("name"), Pin->PinName.ToString());
		PinJson->SetStringField(TEXT("direction"), Pin->Direction == EGPD_Input ? TEXT("Input") : TEXT("Output"));
		PinJson->SetStringField(TEXT("type"), Pin->PinType.PinCategory.ToString());
		PinJson->SetBoolField(TEXT("connected"), Pin->LinkedTo.Num() > 0);

		if (Pin->LinkedTo.Num() > 0)
		{
			TArray<TSharedPtr<FJsonValue>> LinkedArray;
			for (UEdGraphPin* Linked : Pin->LinkedTo)
			{
				if (!Linked) continue;
				UEdGraphNode* LinkedNode = Linked->GetOwningNode();
				if (!LinkedNode) continue;

				FString LinkedId = FBlueprintGraphEditor::GetNodeId(LinkedNode);
				TSharedPtr<FJsonObject> LinkJson = MakeShared<FJsonObject>();
				LinkJson->SetStringField(TEXT("node_id"), LinkedId);
				LinkJson->SetStringField(TEXT("pin_name"), Linked->PinName.ToString());
				LinkedArray.Add(MakeShared<FJsonValueObject>(LinkJson));
			}
			PinJson->SetArrayField(TEXT("linked_to"), LinkedArray);
		}

		if (!Pin->DefaultValue.IsEmpty())
		{
			PinJson->SetStringField(TEXT("default_value"), Pin->DefaultValue);
		}

		PinsArray.Add(MakeShared<FJsonValueObject>(PinJson));
	}
	Json->SetArrayField(TEXT("pins"), PinsArray);

	return Json;
}

// ============================================================================
// Main Entry Points
// ============================================================================

FBlueprintGraphReader::FGraphReadResult FBlueprintGraphReader::ReadEventGraph(
	UBlueprint* Blueprint, const FString& GraphName)
{
	FGraphReadResult Result;
	Result.Metadata = MakeShared<FJsonObject>();

	if (!Blueprint)
	{
		Result.Summary = TEXT("(null blueprint)");
		return Result;
	}

	Result.Metadata->SetStringField(TEXT("blueprint_name"), Blueprint->GetName());

	TArray<UEdGraph*> AllGraphs;
	Blueprint->GetAllGraphs(AllGraphs);

	FString Output;
	Output += FString::Printf(TEXT("============================================================\n"));
	Output += FString::Printf(TEXT("Blueprint Event Graphs: %s\n"), *Blueprint->GetName());
	Output += FString::Printf(TEXT("============================================================\n"));

	TArray<TSharedPtr<FJsonValue>> GraphInfoArray;
	int32 ProcessedGraphs = 0;

	for (UEdGraph* Graph : AllGraphs)
	{
		if (!Graph) continue;

		// Filter by name if specified
		if (!GraphName.IsEmpty() && Graph->GetName() != GraphName)
		{
			continue;
		}

		EGraphType GType = ClassifyGraph(Graph);
		if (GType != EGraphType::EventGraph) continue;

		// Find entry nodes
		TArray<UEdGraphNode*> EntryNodes;
		for (UEdGraphNode* Node : Graph->Nodes)
		{
			if (Cast<UK2Node_Event>(Node) || Cast<UK2Node_CustomEvent>(Node) || Cast<UK2Node_FunctionEntry>(Node))
			{
				EntryNodes.Add(Node);
			}
		}

		if (EntryNodes.Num() == 0)
		{
			// Check if there are any non-intermediate K2 nodes
			bool bHasContent = false;
			for (UEdGraphNode* Node : Graph->Nodes)
			{
				if (Cast<UK2Node>(Node) && !Cast<UK2Node_Knot>(Node))
				{
					bHasContent = true;
					break;
				}
			}
			if (!bHasContent) continue;
		}

		Output += FString::Printf(TEXT("\n--- %s ---\n\n"), *Graph->GetName());
		ProcessedGraphs++;

		TSharedPtr<FJsonObject> GraphMeta = MakeShared<FJsonObject>();
		GraphMeta->SetStringField(TEXT("name"), Graph->GetName());
		GraphMeta->SetStringField(TEXT("type"), TEXT("EventGraph"));
		GraphMeta->SetNumberField(TEXT("node_count"), Graph->Nodes.Num());

		TArray<TSharedPtr<FJsonValue>> NodesArray;
		for (UEdGraphNode* Node : Graph->Nodes)
		{
			if (!Node) continue;
			if (Cast<UK2Node_Knot>(Node)) continue;
			if (Node->GetClass()->GetName().Contains(TEXT("Comment"))) continue;

			NodesArray.Add(MakeShared<FJsonValueObject>(SerializeK2NodeInfo(Node, Graph)));
		}
		GraphMeta->SetArrayField(TEXT("nodes"), NodesArray);
		GraphInfoArray.Add(MakeShared<FJsonValueObject>(GraphMeta));

		if (EntryNodes.Num() == 0)
		{
			Output += TEXT("  (no event/entry nodes found)\n\n");
			continue;
		}

		for (UEdGraphNode* EntryNode : EntryNodes)
		{
			TSet<UEdGraphNode*> Visited;
			WalkExecChain(EntryNode, 0, Output, Visited);
			Output += TEXT("\n");
		}
	}

	if (ProcessedGraphs == 0)
	{
		Output += TEXT("\n(no event graphs found)\n");
	}

	Result.Summary = Output;
	Result.Metadata->SetNumberField(TEXT("graph_count"), ProcessedGraphs);
	Result.Metadata->SetArrayField(TEXT("graphs"), GraphInfoArray);

	return Result;
}

FBlueprintGraphReader::FGraphReadResult FBlueprintGraphReader::ReadAnimGraph(
	UBlueprint* Blueprint, const FString& GraphName)
{
	FGraphReadResult Result;
	Result.Metadata = MakeShared<FJsonObject>();

	if (!Blueprint)
	{
		Result.Summary = TEXT("(null blueprint)");
		return Result;
	}

	Result.Metadata->SetStringField(TEXT("blueprint_name"), Blueprint->GetName());

	TArray<UEdGraph*> AllGraphs;
	Blueprint->GetAllGraphs(AllGraphs);

	FString Output;
	Output += FString::Printf(TEXT("============================================================\n"));
	Output += FString::Printf(TEXT("AnimGraph: %s\n"), *Blueprint->GetName());
	Output += FString::Printf(TEXT("============================================================\n"));

	TArray<TSharedPtr<FJsonValue>> GraphInfoArray;
	int32 ProcessedGraphs = 0;

	for (UEdGraph* Graph : AllGraphs)
	{
		if (!Graph) continue;

		if (!GraphName.IsEmpty() && Graph->GetName() != GraphName)
		{
			continue;
		}

		EGraphType GType = ClassifyGraph(Graph);
		if (GType != EGraphType::AnimGraph) continue;

		// Find Root node
		UAnimGraphNode_Root* RootNode = nullptr;
		for (UEdGraphNode* Node : Graph->Nodes)
		{
			if (UAnimGraphNode_Root* Root = Cast<UAnimGraphNode_Root>(Node))
			{
				RootNode = Root;
				break;
			}
		}

		if (!RootNode) continue;

		Output += FString::Printf(TEXT("\n--- %s (AnimGraph) ---\n\n"), *Graph->GetName());
		ProcessedGraphs++;

		TSharedPtr<FJsonObject> GraphMeta = MakeShared<FJsonObject>();
		GraphMeta->SetStringField(TEXT("name"), Graph->GetName());
		GraphMeta->SetStringField(TEXT("type"), TEXT("AnimGraph"));
		GraphMeta->SetNumberField(TEXT("node_count"), Graph->Nodes.Num());
		GraphInfoArray.Add(MakeShared<FJsonValueObject>(GraphMeta));

		TSet<UEdGraphNode*> Visited;
		WalkPoseChain(RootNode, 0, Output, Visited);

		// Also note K2 nodes in the anim graph (event handlers etc.)
		TArray<UEdGraphNode*> K2Nodes;
		for (UEdGraphNode* Node : Graph->Nodes)
		{
			if (Cast<UK2Node>(Node) && !Cast<UK2Node_Knot>(Node))
			{
				K2Nodes.Add(Node);
			}
		}
		if (K2Nodes.Num() > 0)
		{
			Output += FString::Printf(TEXT("\n  K2 nodes in %s:\n"), *Graph->GetName());
			for (UEdGraphNode* K2Node : K2Nodes)
			{
				FString Label = GetNodeLabel(K2Node);
				if (!Label.IsEmpty())
				{
					Output += FString::Printf(TEXT("    %s\n"), *Label);
				}
			}
		}

		Output += TEXT("\n");
	}

	if (ProcessedGraphs == 0)
	{
		Output += TEXT("\n(no anim graphs found)\n");
	}

	Result.Summary = Output;
	Result.Metadata->SetNumberField(TEXT("graph_count"), ProcessedGraphs);
	Result.Metadata->SetArrayField(TEXT("graphs"), GraphInfoArray);

	return Result;
}

FBlueprintGraphReader::FGraphReadResult FBlueprintGraphReader::ReadStateMachineDetail(
	UBlueprint* Blueprint, const FString& StateMachineName)
{
	FGraphReadResult Result;
	Result.Metadata = MakeShared<FJsonObject>();

	if (!Blueprint)
	{
		Result.Summary = TEXT("(null blueprint)");
		return Result;
	}

	Result.Metadata->SetStringField(TEXT("blueprint_name"), Blueprint->GetName());

	TArray<UEdGraph*> AllGraphs;
	Blueprint->GetAllGraphs(AllGraphs);

	FString Output;
	Output += FString::Printf(TEXT("============================================================\n"));
	Output += FString::Printf(TEXT("State Machine Detail: %s\n"), *Blueprint->GetName());
	Output += FString::Printf(TEXT("============================================================\n"));

	TArray<TSharedPtr<FJsonValue>> SMInfoArray;
	int32 ProcessedSMs = 0;

	// Find state machine nodes in all anim graphs
	for (UEdGraph* Graph : AllGraphs)
	{
		if (!Graph) continue;

		for (UEdGraphNode* Node : Graph->Nodes)
		{
			UAnimGraphNode_StateMachine* SMNode = Cast<UAnimGraphNode_StateMachine>(Node);
			if (!SMNode) continue;

			FString SMName = SMNode->GetStateMachineName();

			// Filter by name if specified
			if (!StateMachineName.IsEmpty() && SMName != StateMachineName)
			{
				continue;
			}

			ProcessedSMs++;
			TSharedPtr<FJsonObject> SMMetadata;
			FormatStateMachine(SMNode, Output, SMMetadata);

			if (SMMetadata.IsValid())
			{
				SMInfoArray.Add(MakeShared<FJsonValueObject>(SMMetadata));
			}
		}
	}

	if (ProcessedSMs == 0)
	{
		Output += TEXT("\n(no state machines found)\n");
	}

	Result.Summary = Output;
	Result.Metadata->SetNumberField(TEXT("state_machine_count"), ProcessedSMs);
	Result.Metadata->SetArrayField(TEXT("state_machines"), SMInfoArray);

	return Result;
}

// ============================================================================
// Helper Utilities
// ============================================================================

FString FBlueprintGraphReader::GraphTypeToString(EGraphType Type)
{
	switch (Type)
	{
	case EGraphType::EventGraph: return TEXT("EventGraph");
	case EGraphType::AnimGraph: return TEXT("AnimGraph");
	case EGraphType::StateMachine: return TEXT("StateMachine");
	default: return TEXT("Other");
	}
}

FString FBlueprintGraphReader::GetOrAssignNodeId(UEdGraphNode* Node, UEdGraph* Graph)
{
	if (!Node) return FString();

	FString NodeId = FBlueprintGraphEditor::GetNodeId(Node);
	if (!NodeId.IsEmpty()) return NodeId;

	if (Cast<UK2Node>(Node))
	{
		FString NodeType, Context;
		DeriveK2NodeTypeAndContext(Node, NodeType, Context);
		NodeId = FBlueprintGraphEditor::GenerateNodeId(NodeType, Context, Graph);
		FBlueprintGraphEditor::SetNodeId(Node, NodeId);
		return NodeId;
	}

	return Node->GetName();
}

// ============================================================================
// Anim Node Serialization
// ============================================================================

TSharedPtr<FJsonObject> FBlueprintGraphReader::SerializeAnimNodeInfo(UEdGraphNode* Node, UEdGraph* Graph)
{
	TSharedPtr<FJsonObject> Json = MakeShared<FJsonObject>();
	if (!Node) return Json;

	FString NodeId = GetOrAssignNodeId(Node, Graph);
	Json->SetStringField(TEXT("node_id"), NodeId);
	Json->SetStringField(TEXT("node_class"), Node->GetClass()->GetName());
	Json->SetStringField(TEXT("label"), GetAnimNodeLabel(Node));
	if (Graph)
	{
		Json->SetStringField(TEXT("graph_name"), Graph->GetName());
	}
	Json->SetNumberField(TEXT("pos_x"), Node->NodePosX);
	Json->SetNumberField(TEXT("pos_y"), Node->NodePosY);

	TSharedPtr<FJsonObject> AnimProps = MakeShared<FJsonObject>();

	if (UAnimGraphNode_SequencePlayer* SeqPlayer = Cast<UAnimGraphNode_SequencePlayer>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("SequencePlayer"));
		UAnimationAsset* Seq = SeqPlayer->Node.GetSequence();
		if (Seq)
		{
			AnimProps->SetStringField(TEXT("animation"), Seq->GetPathName());
		}
	}
	else if (UAnimGraphNode_BlendSpacePlayer* BSPlayer = Cast<UAnimGraphNode_BlendSpacePlayer>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("BlendSpacePlayer"));
		UBlendSpace* BS = Cast<UBlendSpace>(BSPlayer->Node.GetBlendSpace());
		if (BS)
		{
			AnimProps->SetStringField(TEXT("blend_space"), BS->GetPathName());
		}
	}
	else if (UAnimGraphNode_StateMachine* SM = Cast<UAnimGraphNode_StateMachine>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("StateMachine"));
		AnimProps->SetStringField(TEXT("machine_name"), SM->GetStateMachineName());
	}
	else if (UAnimGraphNode_Slot* Slot = Cast<UAnimGraphNode_Slot>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("Slot"));
		AnimProps->SetStringField(TEXT("slot_name"), Slot->Node.SlotName.ToString());
	}
	else if (UAnimGraphNode_SaveCachedPose* SavePose = Cast<UAnimGraphNode_SaveCachedPose>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("SaveCachedPose"));
		AnimProps->SetStringField(TEXT("cache_name"), SavePose->CacheName);
	}
	else if (UAnimGraphNode_UseCachedPose* UsePose = Cast<UAnimGraphNode_UseCachedPose>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("UseCachedPose"));
		AnimProps->SetStringField(TEXT("cache_name"), UsePose->GetNodeTitle(ENodeTitleType::ListView).ToString());
	}
	else if (UAnimGraphNode_LinkedAnimLayer* LayerNode = Cast<UAnimGraphNode_LinkedAnimLayer>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("LinkedAnimLayer"));
		AnimProps->SetStringField(TEXT("layer"), LayerNode->Node.Layer.ToString());
		UClass* InterfaceClass = *LayerNode->Node.Interface;
		if (InterfaceClass)
		{
			AnimProps->SetStringField(TEXT("interface_class"), InterfaceClass->GetName());
		}
	}
	else if (UAnimGraphNode_LinkedAnimGraph* LinkedGraph = Cast<UAnimGraphNode_LinkedAnimGraph>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("LinkedAnimGraph"));
	}
	else if (Cast<UAnimGraphNode_LayeredBoneBlend>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("LayeredBoneBlend"));
	}
	else if (Cast<UAnimGraphNode_BlendListByBool>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("BlendListByBool"));
	}
	else if (Cast<UAnimGraphNode_BlendListByEnum>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("BlendListByEnum"));
	}
	else if (Cast<UAnimGraphNode_Root>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("Root"));
	}
	else if (Cast<UAnimGraphNode_StateResult>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("StateResult"));
	}
	else if (Cast<UAnimGraphNode_TransitionResult>(Node))
	{
		AnimProps->SetStringField(TEXT("type"), TEXT("TransitionResult"));
	}
	else
	{
		AnimProps->SetStringField(TEXT("type"), Node->GetClass()->GetName());
	}

	Json->SetObjectField(TEXT("anim_properties"), AnimProps);

	TArray<TSharedPtr<FJsonValue>> PinsArray;
	for (UEdGraphPin* Pin : Node->Pins)
	{
		if (!Pin || Pin->bHidden) continue;

		TSharedPtr<FJsonObject> PinJson = MakeShared<FJsonObject>();
		PinJson->SetStringField(TEXT("name"), Pin->PinName.ToString());
		PinJson->SetStringField(TEXT("direction"), Pin->Direction == EGPD_Input ? TEXT("Input") : TEXT("Output"));

		FString PinCategory = Pin->PinType.PinCategory.ToString();
		if (IsPoseLinkPin(Pin))
		{
			PinCategory = TEXT("PoseLink");
		}
		PinJson->SetStringField(TEXT("type"), PinCategory);
		PinJson->SetBoolField(TEXT("connected"), Pin->LinkedTo.Num() > 0);

		if (Pin->LinkedTo.Num() > 0)
		{
			TArray<TSharedPtr<FJsonValue>> LinkedArray;
			for (UEdGraphPin* Linked : Pin->LinkedTo)
			{
				if (!Linked) continue;
				UEdGraphNode* LinkedNode = Linked->GetOwningNode();
				if (!LinkedNode) continue;

				FString LinkedId = FBlueprintGraphEditor::GetNodeId(LinkedNode);
				if (LinkedId.IsEmpty()) LinkedId = LinkedNode->GetName();

				TSharedPtr<FJsonObject> LinkJson = MakeShared<FJsonObject>();
				LinkJson->SetStringField(TEXT("node_id"), LinkedId);
				LinkJson->SetStringField(TEXT("pin_name"), Linked->PinName.ToString());
				LinkedArray.Add(MakeShared<FJsonValueObject>(LinkJson));
			}
			PinJson->SetArrayField(TEXT("linked_to"), LinkedArray);
		}

		if (!Pin->DefaultValue.IsEmpty())
		{
			PinJson->SetStringField(TEXT("default_value"), Pin->DefaultValue);
		}

		PinsArray.Add(MakeShared<FJsonValueObject>(PinJson));
	}
	Json->SetArrayField(TEXT("pins"), PinsArray);

	return Json;
}

// ============================================================================
// State-Bound Graph Discovery
// ============================================================================

TArray<FBlueprintGraphReader::FStateBoundGraph> FBlueprintGraphReader::CollectStateBoundGraphs(UBlueprint* Blueprint)
{
	TArray<FStateBoundGraph> Result;
	if (!Blueprint) return Result;

	TArray<UEdGraph*> AllGraphs;
	Blueprint->GetAllGraphs(AllGraphs);

	for (UEdGraph* Graph : AllGraphs)
	{
		if (!Graph) continue;
		for (UEdGraphNode* Node : Graph->Nodes)
		{
			UAnimGraphNode_StateMachine* SMNode = Cast<UAnimGraphNode_StateMachine>(Node);
			if (!SMNode || !SMNode->EditorStateMachineGraph) continue;

			FString SMName = SMNode->GetStateMachineName();
			for (UEdGraphNode* SMChild : SMNode->EditorStateMachineGraph->Nodes)
			{
				UAnimStateNode* StateNode = Cast<UAnimStateNode>(SMChild);
				if (!StateNode) continue;

				UEdGraph* BoundGraph = StateNode->GetBoundGraph();
				if (!BoundGraph) continue;

				FStateBoundGraph Entry;
				Entry.Graph = BoundGraph;
				Entry.StateMachineName = SMName;
				Entry.StateName = StateNode->GetNodeTitle(ENodeTitleType::ListView).ToString();
				Result.Add(Entry);
			}
		}
	}

	return Result;
}

// ============================================================================
// Cross-Graph Node Lookup
// ============================================================================

FBlueprintGraphReader::FNodeSearchResult FBlueprintGraphReader::FindNodeByIdAcrossGraphs(
	UBlueprint* Blueprint, const FString& NodeId, const FString& GraphNameHint)
{
	FNodeSearchResult Result;
	if (!Blueprint || NodeId.IsEmpty()) return Result;

	TArray<UEdGraph*> AllGraphs;
	Blueprint->GetAllGraphs(AllGraphs);

	auto SearchGraph = [&](UEdGraph* Graph) -> bool
	{
		if (!Graph) return false;
		UEdGraphNode* Found = FBlueprintGraphEditor::FindNodeById(Graph, NodeId);
		if (Found)
		{
			Result.Node = Found;
			Result.Graph = Graph;
			Result.GraphName = Graph->GetName();
			Result.GraphType = GraphTypeToString(ClassifyGraph(Graph));
			return true;
		}
		return false;
	};

	if (!GraphNameHint.IsEmpty())
	{
		for (UEdGraph* Graph : AllGraphs)
		{
			if (Graph && Graph->GetName() == GraphNameHint)
			{
				if (SearchGraph(Graph)) return Result;
				break;
			}
		}
	}

	for (UEdGraph* Graph : AllGraphs)
	{
		if (SearchGraph(Graph)) return Result;
	}

	// Fallback: search state-bound graphs (not included in GetAllGraphs)
	for (const FStateBoundGraph& SBG : CollectStateBoundGraphs(Blueprint))
	{
		UEdGraphNode* Found = FBlueprintGraphEditor::FindNodeById(SBG.Graph, NodeId);
		if (Found)
		{
			Result.Node = Found;
			Result.Graph = SBG.Graph;
			Result.GraphName = SBG.Graph->GetName();
			Result.GraphType = TEXT("StateGraph");
			return Result;
		}
	}

	return Result;
}

// ============================================================================
// find_nodes
// ============================================================================

TSharedPtr<FJsonObject> FBlueprintGraphReader::FindNodes(UBlueprint* Blueprint,
	const FString& Search, const FString& NodeClass, const FString& GraphName, const FString& GraphType)
{
	TSharedPtr<FJsonObject> Response = MakeShared<FJsonObject>();
	if (!Blueprint)
	{
		Response->SetStringField(TEXT("error"), TEXT("null blueprint"));
		return Response;
	}

	TArray<UEdGraph*> AllGraphs;
	Blueprint->GetAllGraphs(AllGraphs);

	TArray<TSharedPtr<FJsonValue>> ResultsArray;

	for (UEdGraph* Graph : AllGraphs)
	{
		if (!Graph) continue;

		if (!GraphName.IsEmpty() && Graph->GetName() != GraphName)
		{
			continue;
		}

		EGraphType GType = ClassifyGraph(Graph);
		FString GTypeStr = GraphTypeToString(GType);

		if (!GraphType.IsEmpty() && !GraphType.Equals(TEXT("All"), ESearchCase::IgnoreCase))
		{
			if (!GTypeStr.Equals(GraphType, ESearchCase::IgnoreCase))
			{
				continue;
			}
		}

		for (UEdGraphNode* Node : Graph->Nodes)
		{
			if (!Node) continue;
			if (Cast<UK2Node_Knot>(Node)) continue;
			if (Node->GetClass()->GetName().Contains(TEXT("Comment"))) continue;

			if (!NodeClass.IsEmpty())
			{
				FString ClassName = Node->GetClass()->GetName();
				if (!ClassName.Contains(NodeClass, ESearchCase::IgnoreCase))
				{
					continue;
				}
			}

			FString Label = GetNodeLabel(Node);

			if (!Search.IsEmpty())
			{
				if (!Label.Contains(Search, ESearchCase::IgnoreCase))
				{
					continue;
				}
			}

			FString NodeId = GetOrAssignNodeId(Node, Graph);

			int32 PinCount = 0;
			int32 ConnectedPinCount = 0;
			for (UEdGraphPin* Pin : Node->Pins)
			{
				if (Pin && !Pin->bHidden)
				{
					PinCount++;
					if (Pin->LinkedTo.Num() > 0) ConnectedPinCount++;
				}
			}

			TSharedPtr<FJsonObject> NodeJson = MakeShared<FJsonObject>();
			NodeJson->SetStringField(TEXT("node_id"), NodeId);
			NodeJson->SetStringField(TEXT("label"), Label);
			NodeJson->SetStringField(TEXT("node_class"), Node->GetClass()->GetName());
			NodeJson->SetStringField(TEXT("graph_name"), Graph->GetName());
			NodeJson->SetStringField(TEXT("graph_type"), GTypeStr);
			NodeJson->SetNumberField(TEXT("pos_x"), Node->NodePosX);
			NodeJson->SetNumberField(TEXT("pos_y"), Node->NodePosY);
			NodeJson->SetNumberField(TEXT("pin_count"), PinCount);
			NodeJson->SetNumberField(TEXT("connected_pin_count"), ConnectedPinCount);

			ResultsArray.Add(MakeShared<FJsonValueObject>(NodeJson));
		}
	}

	// Also search state-bound graphs
	bool bWantStateGraphs = GraphType.IsEmpty()
		|| GraphType.Equals(TEXT("All"), ESearchCase::IgnoreCase)
		|| GraphType.Equals(TEXT("AnimGraph"), ESearchCase::IgnoreCase)
		|| GraphType.Equals(TEXT("StateGraph"), ESearchCase::IgnoreCase);

	if (bWantStateGraphs && GraphName.IsEmpty())
	{
		for (const FStateBoundGraph& SBG : CollectStateBoundGraphs(Blueprint))
		{
			for (UEdGraphNode* Node : SBG.Graph->Nodes)
			{
				if (!Node) continue;
				if (Node->GetClass()->GetName().Contains(TEXT("Comment"))) continue;

				if (!NodeClass.IsEmpty())
				{
					FString ClassName = Node->GetClass()->GetName();
					if (!ClassName.Contains(NodeClass, ESearchCase::IgnoreCase))
					{
						continue;
					}
				}

				FString Label = GetNodeLabel(Node);
				if (!Search.IsEmpty() && !Label.Contains(Search, ESearchCase::IgnoreCase))
				{
					continue;
				}

				FString NodeId = GetOrAssignNodeId(Node, SBG.Graph);

				int32 PinCount = 0;
				int32 ConnectedPinCount = 0;
				for (UEdGraphPin* Pin : Node->Pins)
				{
					if (Pin && !Pin->bHidden)
					{
						PinCount++;
						if (Pin->LinkedTo.Num() > 0) ConnectedPinCount++;
					}
				}

				TSharedPtr<FJsonObject> NodeJson = MakeShared<FJsonObject>();
				NodeJson->SetStringField(TEXT("node_id"), NodeId);
				NodeJson->SetStringField(TEXT("label"), Label);
				NodeJson->SetStringField(TEXT("node_class"), Node->GetClass()->GetName());
				NodeJson->SetStringField(TEXT("graph_name"), SBG.Graph->GetName());
				NodeJson->SetStringField(TEXT("graph_type"), TEXT("StateGraph"));
				NodeJson->SetStringField(TEXT("state_machine"), SBG.StateMachineName);
				NodeJson->SetStringField(TEXT("state_name"), SBG.StateName);
				NodeJson->SetNumberField(TEXT("pos_x"), Node->NodePosX);
				NodeJson->SetNumberField(TEXT("pos_y"), Node->NodePosY);
				NodeJson->SetNumberField(TEXT("pin_count"), PinCount);
				NodeJson->SetNumberField(TEXT("connected_pin_count"), ConnectedPinCount);

				ResultsArray.Add(MakeShared<FJsonValueObject>(NodeJson));
			}
		}
	}

	Response->SetArrayField(TEXT("nodes"), ResultsArray);
	Response->SetNumberField(TEXT("count"), ResultsArray.Num());
	return Response;
}

// ============================================================================
// get_node
// ============================================================================

TSharedPtr<FJsonObject> FBlueprintGraphReader::GetNode(UBlueprint* Blueprint,
	const FString& NodeId, const FString& GraphName)
{
	TSharedPtr<FJsonObject> Response = MakeShared<FJsonObject>();
	if (!Blueprint)
	{
		Response->SetStringField(TEXT("error"), TEXT("null blueprint"));
		return Response;
	}

	FNodeSearchResult Found = FindNodeByIdAcrossGraphs(Blueprint, NodeId, GraphName);
	if (!Found.Node)
	{
		Response->SetStringField(TEXT("error"), FString::Printf(TEXT("Node '%s' not found"), *NodeId));
		return Response;
	}

	if (Cast<UAnimGraphNode_Base>(Found.Node) || Cast<UAnimStateNodeBase>(Found.Node) || Cast<UAnimStateEntryNode>(Found.Node))
	{
		Response = SerializeAnimNodeInfo(Found.Node, Found.Graph);
	}
	else
	{
		Response = SerializeK2NodeInfo(Found.Node, Found.Graph);
	}

	Response->SetStringField(TEXT("graph_name"), Found.GraphName);
	Response->SetStringField(TEXT("graph_type"), Found.GraphType);

	return Response;
}

// ============================================================================
// verify_connection
// ============================================================================

TSharedPtr<FJsonObject> FBlueprintGraphReader::VerifyConnection(UBlueprint* Blueprint,
	const FString& SourceNodeId, const FString& TargetNodeId,
	const FString& SourcePin, const FString& TargetPin)
{
	TSharedPtr<FJsonObject> Response = MakeShared<FJsonObject>();
	if (!Blueprint)
	{
		Response->SetStringField(TEXT("error"), TEXT("null blueprint"));
		return Response;
	}

	FNodeSearchResult SourceResult = FindNodeByIdAcrossGraphs(Blueprint, SourceNodeId);
	if (!SourceResult.Node)
	{
		Response->SetStringField(TEXT("error"), FString::Printf(TEXT("Source node '%s' not found"), *SourceNodeId));
		return Response;
	}

	FNodeSearchResult TargetResult = FindNodeByIdAcrossGraphs(Blueprint, TargetNodeId);
	if (!TargetResult.Node)
	{
		Response->SetStringField(TEXT("error"), FString::Printf(TEXT("Target node '%s' not found"), *TargetNodeId));
		return Response;
	}

	Response->SetBoolField(TEXT("connected"), false);
	Response->SetStringField(TEXT("source_label"), GetNodeLabel(SourceResult.Node));
	Response->SetStringField(TEXT("target_label"), GetNodeLabel(TargetResult.Node));

	for (UEdGraphPin* SPin : SourceResult.Node->Pins)
	{
		if (!SPin || SPin->Direction != EGPD_Output) continue;
		if (!SourcePin.IsEmpty() && !SPin->PinName.ToString().Equals(SourcePin, ESearchCase::IgnoreCase)) continue;

		for (UEdGraphPin* Linked : SPin->LinkedTo)
		{
			if (!Linked) continue;
			UEdGraphNode* LinkedNode = Linked->GetOwningNode();
			if (!LinkedNode) continue;

			UEdGraphNode* ResolvedNode = FollowThroughKnots(LinkedNode, EGPD_Output);

			bool bMatch = (ResolvedNode == TargetResult.Node) || (LinkedNode == TargetResult.Node);
			if (!bMatch) continue;

			if (!TargetPin.IsEmpty() && !Linked->PinName.ToString().Equals(TargetPin, ESearchCase::IgnoreCase)) continue;

			Response->SetBoolField(TEXT("connected"), true);
			Response->SetStringField(TEXT("source_pin"), SPin->PinName.ToString());
			Response->SetStringField(TEXT("target_pin"), Linked->PinName.ToString());
			return Response;
		}
	}

	for (UEdGraphPin* SPin : SourceResult.Node->Pins)
	{
		if (!SPin || SPin->Direction != EGPD_Input) continue;
		if (!SourcePin.IsEmpty() && !SPin->PinName.ToString().Equals(SourcePin, ESearchCase::IgnoreCase)) continue;

		for (UEdGraphPin* Linked : SPin->LinkedTo)
		{
			if (!Linked) continue;
			UEdGraphNode* LinkedNode = Linked->GetOwningNode();
			if (!LinkedNode) continue;

			UEdGraphNode* ResolvedNode = FollowThroughKnots(LinkedNode, EGPD_Input);

			bool bMatch = (ResolvedNode == TargetResult.Node) || (LinkedNode == TargetResult.Node);
			if (!bMatch) continue;

			if (!TargetPin.IsEmpty() && !Linked->PinName.ToString().Equals(TargetPin, ESearchCase::IgnoreCase)) continue;

			Response->SetBoolField(TEXT("connected"), true);
			Response->SetStringField(TEXT("source_pin"), SPin->PinName.ToString());
			Response->SetStringField(TEXT("target_pin"), Linked->PinName.ToString());
			return Response;
		}
	}

	return Response;
}

// ============================================================================
// get_node_connections
// ============================================================================

TSharedPtr<FJsonObject> FBlueprintGraphReader::GetNodeConnections(UBlueprint* Blueprint,
	const FString& NodeId, const FString& Direction, const FString& PinFilter)
{
	TSharedPtr<FJsonObject> Response = MakeShared<FJsonObject>();
	if (!Blueprint)
	{
		Response->SetStringField(TEXT("error"), TEXT("null blueprint"));
		return Response;
	}

	FNodeSearchResult Found = FindNodeByIdAcrossGraphs(Blueprint, NodeId);
	if (!Found.Node)
	{
		Response->SetStringField(TEXT("error"), FString::Printf(TEXT("Node '%s' not found"), *NodeId));
		return Response;
	}

	TSet<FString> AllowedPins;
	if (!PinFilter.IsEmpty())
	{
		TArray<FString> FilterParts;
		PinFilter.ParseIntoArray(FilterParts, TEXT(","));
		for (FString& Part : FilterParts)
		{
			AllowedPins.Add(Part.TrimStartAndEnd());
		}
	}

	bool bWantInput = Direction.IsEmpty() || Direction.Equals(TEXT("both"), ESearchCase::IgnoreCase)
		|| Direction.Equals(TEXT("input"), ESearchCase::IgnoreCase);
	bool bWantOutput = Direction.IsEmpty() || Direction.Equals(TEXT("both"), ESearchCase::IgnoreCase)
		|| Direction.Equals(TEXT("output"), ESearchCase::IgnoreCase);

	Response->SetStringField(TEXT("node_id"), GetOrAssignNodeId(Found.Node, Found.Graph));
	Response->SetStringField(TEXT("label"), GetNodeLabel(Found.Node));

	TSharedPtr<FJsonObject> Connections = MakeShared<FJsonObject>();
	TArray<TSharedPtr<FJsonValue>> InputConns, OutputConns;
	TArray<TSharedPtr<FJsonValue>> UnconnectedInput, UnconnectedOutput;

	for (UEdGraphPin* Pin : Found.Node->Pins)
	{
		if (!Pin || Pin->bHidden) continue;

		FString PinName = Pin->PinName.ToString();
		if (AllowedPins.Num() > 0 && !AllowedPins.Contains(PinName)) continue;

		bool bIsInput = Pin->Direction == EGPD_Input;
		if (bIsInput && !bWantInput) continue;
		if (!bIsInput && !bWantOutput) continue;

		if (Pin->LinkedTo.Num() == 0)
		{
			TSharedPtr<FJsonObject> UnconnJson = MakeShared<FJsonObject>();
			UnconnJson->SetStringField(TEXT("pin_name"), PinName);

			FString PinCategory = Pin->PinType.PinCategory.ToString();
			if (IsPoseLinkPin(Pin)) PinCategory = TEXT("PoseLink");
			else if (IsExecPin(Pin)) PinCategory = TEXT("Exec");
			UnconnJson->SetStringField(TEXT("pin_type"), PinCategory);

			if (!Pin->DefaultValue.IsEmpty())
			{
				UnconnJson->SetStringField(TEXT("default_value"), Pin->DefaultValue);
			}

			if (bIsInput)
				UnconnectedInput.Add(MakeShared<FJsonValueObject>(UnconnJson));
			else
				UnconnectedOutput.Add(MakeShared<FJsonValueObject>(UnconnJson));
			continue;
		}

		for (UEdGraphPin* Linked : Pin->LinkedTo)
		{
			if (!Linked) continue;
			UEdGraphNode* LinkedNode = Linked->GetOwningNode();
			if (!LinkedNode) continue;

			UEdGraphNode* Resolved = FollowThroughKnots(LinkedNode,
				bIsInput ? EGPD_Input : EGPD_Output);
			if (Resolved) LinkedNode = Resolved;

			FString LinkedId = FBlueprintGraphEditor::GetNodeId(LinkedNode);
			if (LinkedId.IsEmpty()) LinkedId = LinkedNode->GetName();

			TSharedPtr<FJsonObject> ConnJson = MakeShared<FJsonObject>();
			ConnJson->SetStringField(TEXT("pin_name"), PinName);

			FString PinCategory = Pin->PinType.PinCategory.ToString();
			if (IsPoseLinkPin(Pin)) PinCategory = TEXT("PoseLink");
			else if (IsExecPin(Pin)) PinCategory = TEXT("Exec");
			ConnJson->SetStringField(TEXT("pin_type"), PinCategory);

			TSharedPtr<FJsonObject> ConnectedTo = MakeShared<FJsonObject>();
			ConnectedTo->SetStringField(TEXT("node_id"), LinkedId);
			ConnectedTo->SetStringField(TEXT("pin_name"), Linked->PinName.ToString());
			ConnectedTo->SetStringField(TEXT("label"), GetNodeLabel(LinkedNode));
			ConnJson->SetObjectField(TEXT("connected_to"), ConnectedTo);

			if (bIsInput)
				InputConns.Add(MakeShared<FJsonValueObject>(ConnJson));
			else
				OutputConns.Add(MakeShared<FJsonValueObject>(ConnJson));
		}
	}

	Connections->SetArrayField(TEXT("input"), InputConns);
	Connections->SetArrayField(TEXT("output"), OutputConns);
	Response->SetObjectField(TEXT("connections"), Connections);

	TSharedPtr<FJsonObject> Unconnected = MakeShared<FJsonObject>();
	Unconnected->SetArrayField(TEXT("input"), UnconnectedInput);
	Unconnected->SetArrayField(TEXT("output"), UnconnectedOutput);
	Response->SetObjectField(TEXT("unconnected_pins"), Unconnected);

	return Response;
}

// ============================================================================
// get_graph_summary
// ============================================================================

TSharedPtr<FJsonObject> FBlueprintGraphReader::GetGraphSummary(UBlueprint* Blueprint,
	const FString& GraphName, const FString& GraphType)
{
	TSharedPtr<FJsonObject> Response = MakeShared<FJsonObject>();
	if (!Blueprint)
	{
		Response->SetStringField(TEXT("error"), TEXT("null blueprint"));
		return Response;
	}

	TArray<UEdGraph*> AllGraphs;
	Blueprint->GetAllGraphs(AllGraphs);

	TArray<TSharedPtr<FJsonValue>> GraphsArray;

	for (UEdGraph* Graph : AllGraphs)
	{
		if (!Graph) continue;

		if (!GraphName.IsEmpty() && Graph->GetName() != GraphName)
		{
			continue;
		}

		EGraphType GType = ClassifyGraph(Graph);
		FString GTypeStr = GraphTypeToString(GType);

		if (!GraphType.IsEmpty() && !GraphType.Equals(TEXT("All"), ESearchCase::IgnoreCase))
		{
			if (!GTypeStr.Equals(GraphType, ESearchCase::IgnoreCase))
			{
				continue;
			}
		}

		TSharedPtr<FJsonObject> GraphJson = MakeShared<FJsonObject>();
		GraphJson->SetStringField(TEXT("name"), Graph->GetName());
		GraphJson->SetStringField(TEXT("type"), GTypeStr);

		TMap<FString, int32> NodesByType;
		TArray<TSharedPtr<FJsonValue>> EntryPoints;
		TArray<TSharedPtr<FJsonValue>> AllNodeIds;
		int32 TotalNodes = 0;

		for (UEdGraphNode* Node : Graph->Nodes)
		{
			if (!Node) continue;
			if (Cast<UK2Node_Knot>(Node)) continue;
			if (Node->GetClass()->GetName().Contains(TEXT("Comment"))) continue;

			TotalNodes++;

			FString NodeId = GetOrAssignNodeId(Node, Graph);
			AllNodeIds.Add(MakeShared<FJsonValueString>(NodeId));

			FString TypeBucket;
			if (Cast<UK2Node_Event>(Node) || Cast<UK2Node_CustomEvent>(Node))
			{
				TypeBucket = TEXT("Event");
			}
			else if (Cast<UK2Node_FunctionEntry>(Node))
			{
				TypeBucket = TEXT("FunctionEntry");
			}
			else if (Cast<UK2Node_CallFunction>(Node))
			{
				TypeBucket = TEXT("CallFunction");
			}
			else if (Cast<UK2Node_VariableGet>(Node))
			{
				TypeBucket = TEXT("VarGet");
			}
			else if (Cast<UK2Node_VariableSet>(Node))
			{
				TypeBucket = TEXT("VarSet");
			}
			else if (Cast<UK2Node_IfThenElse>(Node))
			{
				TypeBucket = TEXT("Branch");
			}
			else if (Cast<UAnimGraphNode_Root>(Node))
			{
				TypeBucket = TEXT("AnimRoot");
			}
			else if (Cast<UAnimGraphNode_StateMachine>(Node))
			{
				TypeBucket = TEXT("StateMachine");
			}
			else if (Cast<UAnimGraphNode_Base>(Node))
			{
				TypeBucket = TEXT("AnimNode");
			}
			else if (Cast<UAnimStateNode>(Node))
			{
				TypeBucket = TEXT("State");
			}
			else if (Cast<UAnimStateTransitionNode>(Node))
			{
				TypeBucket = TEXT("Transition");
			}
			else if (Cast<UAnimStateEntryNode>(Node))
			{
				TypeBucket = TEXT("Entry");
			}
			else
			{
				TypeBucket = Node->GetClass()->GetName();
			}

			NodesByType.FindOrAdd(TypeBucket)++;

			bool bIsEntry = Cast<UK2Node_Event>(Node) || Cast<UK2Node_CustomEvent>(Node)
				|| Cast<UK2Node_FunctionEntry>(Node) || Cast<UAnimGraphNode_Root>(Node)
				|| Cast<UAnimStateEntryNode>(Node);

			if (bIsEntry)
			{
				TSharedPtr<FJsonObject> EntryJson = MakeShared<FJsonObject>();
				EntryJson->SetStringField(TEXT("node_id"), NodeId);
				EntryJson->SetStringField(TEXT("label"), GetNodeLabel(Node));
				EntryPoints.Add(MakeShared<FJsonValueObject>(EntryJson));
			}
		}

		GraphJson->SetNumberField(TEXT("total_nodes"), TotalNodes);

		TSharedPtr<FJsonObject> NodesByTypeJson = MakeShared<FJsonObject>();
		for (auto& Pair : NodesByType)
		{
			NodesByTypeJson->SetNumberField(Pair.Key, Pair.Value);
		}
		GraphJson->SetObjectField(TEXT("nodes_by_type"), NodesByTypeJson);
		GraphJson->SetArrayField(TEXT("entry_points"), EntryPoints);
		GraphJson->SetArrayField(TEXT("all_node_ids"), AllNodeIds);

		GraphsArray.Add(MakeShared<FJsonValueObject>(GraphJson));
	}

	// Include state-bound graphs when appropriate
	bool bWantStateGraphs = GraphType.IsEmpty()
		|| GraphType.Equals(TEXT("All"), ESearchCase::IgnoreCase)
		|| GraphType.Equals(TEXT("AnimGraph"), ESearchCase::IgnoreCase)
		|| GraphType.Equals(TEXT("StateGraph"), ESearchCase::IgnoreCase);

	if (bWantStateGraphs && GraphName.IsEmpty())
	{
		for (const FStateBoundGraph& SBG : CollectStateBoundGraphs(Blueprint))
		{
			TSharedPtr<FJsonObject> GraphJson = MakeShared<FJsonObject>();
			GraphJson->SetStringField(TEXT("name"), SBG.Graph->GetName());
			GraphJson->SetStringField(TEXT("type"), TEXT("StateGraph"));
			GraphJson->SetStringField(TEXT("state_machine"), SBG.StateMachineName);
			GraphJson->SetStringField(TEXT("state_name"), SBG.StateName);

			TMap<FString, int32> NodesByType;
			TArray<TSharedPtr<FJsonValue>> AllNodeIds;
			int32 TotalNodes = 0;

			for (UEdGraphNode* Node : SBG.Graph->Nodes)
			{
				if (!Node) continue;
				if (Node->GetClass()->GetName().Contains(TEXT("Comment"))) continue;

				TotalNodes++;
				FString NodeId = GetOrAssignNodeId(Node, SBG.Graph);
				AllNodeIds.Add(MakeShared<FJsonValueString>(NodeId));

				FString TypeBucket;
				if (Cast<UAnimGraphNode_StateResult>(Node))
					TypeBucket = TEXT("StateResult");
				else if (Cast<UAnimGraphNode_Base>(Node))
					TypeBucket = TEXT("AnimNode");
				else if (Cast<UK2Node_VariableGet>(Node))
					TypeBucket = TEXT("VarGet");
				else if (Cast<UK2Node>(Node))
					TypeBucket = TEXT("K2Node");
				else
					TypeBucket = Node->GetClass()->GetName();

				NodesByType.FindOrAdd(TypeBucket)++;
			}

			GraphJson->SetNumberField(TEXT("total_nodes"), TotalNodes);

			TSharedPtr<FJsonObject> NodesByTypeJson = MakeShared<FJsonObject>();
			for (auto& Pair : NodesByType)
			{
				NodesByTypeJson->SetNumberField(Pair.Key, Pair.Value);
			}
			GraphJson->SetObjectField(TEXT("nodes_by_type"), NodesByTypeJson);
			GraphJson->SetArrayField(TEXT("entry_points"), TArray<TSharedPtr<FJsonValue>>());
			GraphJson->SetArrayField(TEXT("all_node_ids"), AllNodeIds);

			GraphsArray.Add(MakeShared<FJsonValueObject>(GraphJson));
		}
	}

	Response->SetArrayField(TEXT("graphs"), GraphsArray);
	Response->SetNumberField(TEXT("graph_count"), GraphsArray.Num());
	return Response;
}

// ============================================================================
// get_exec_chain
// ============================================================================

TSharedPtr<FJsonObject> FBlueprintGraphReader::GetExecChain(UBlueprint* Blueprint,
	const FString& NodeId, int32 MaxDepth)
{
	TSharedPtr<FJsonObject> Response = MakeShared<FJsonObject>();
	if (!Blueprint)
	{
		Response->SetStringField(TEXT("error"), TEXT("null blueprint"));
		return Response;
	}

	FNodeSearchResult Found = FindNodeByIdAcrossGraphs(Blueprint, NodeId);
	if (!Found.Node)
	{
		Response->SetStringField(TEXT("error"), FString::Printf(TEXT("Node '%s' not found"), *NodeId));
		return Response;
	}

	Response->SetStringField(TEXT("start_node"), NodeId);
	Response->SetStringField(TEXT("start_label"), GetNodeLabel(Found.Node));

	FString Output;
	TSet<UEdGraphNode*> Visited;
	TArray<FString> VisitedIds;

	WalkExecChain(Found.Node, 0, Output, Visited, &VisitedIds);

	Response->SetStringField(TEXT("chain_summary"), Output);

	TArray<TSharedPtr<FJsonValue>> IdsArray;
	for (const FString& Id : VisitedIds)
	{
		IdsArray.Add(MakeShared<FJsonValueString>(Id));
	}
	Response->SetArrayField(TEXT("nodes_in_chain"), IdsArray);
	Response->SetNumberField(TEXT("node_count"), VisitedIds.Num());
	Response->SetBoolField(TEXT("max_depth_reached"), Visited.Num() >= MaxDepth);

	return Response;
}
